export const STATUSES = [
  "NEW",
  "IN_PROGRESS",
  "DONE",
  "SENT_TO_CLIENT",
  "REWORK",
  "OVERDUE",
] as const;

export type TaskStatus = (typeof STATUSES)[number];

export const STATUS_LABELS: Record<TaskStatus, string> = {
  NEW: "Новые",
  IN_PROGRESS: "Ежедневник у сотрудников",
  DONE: "Выполнено",
  SENT_TO_CLIENT: "Отправлено клиенту",
  REWORK: "На доработке",
  OVERDUE: "Просрочено",
};

export const STATUS_COLORS: Record<TaskStatus, string> = {
  NEW: "border-zinc-200 bg-zinc-50",
  IN_PROGRESS: "border-blue-200 bg-blue-50",
  DONE: "border-green-200 bg-green-50",
  SENT_TO_CLIENT: "border-violet-200 bg-violet-50",
  REWORK: "border-amber-200 bg-amber-50",
  OVERDUE: "border-red-200 bg-red-50",
};

export const TASK_TYPE_LABELS: Record<string, string> = {
  SALARY_CALC: "Расчёт ЗП",
  SALARY_PAYMENT: "Выплата ЗП",
  SALARY_ADVANCE: "Аванс",
  SALARY_SICK_LEAVE: "Расчёт больничного",
  SALARY_VACATION: "Расчёт отпускных",
  SALARY_BONUS: "Начисление премии",
  TAX_PAYMENT: "Уплата налога",
  REPORT: "Отчётность",
  REPORT_VAT_DECL: "Декларация по НДС",
  REPORT_VAT_PAY: "Уплата НДС",
  REPORT_PROFIT_DECL: "Декларация по налогу на прибыль",
  REPORT_PROFIT_PAY: "Уплата налога на прибыль",
  REPORT_NDFL_6: "6-НДФЛ",
  REPORT_NDFL_PAY: "НДФЛ: уплата",
  REPORT_NDFL_AUSN: "НДФЛ для АУСН",
  REPORT_NDFL_NOTICE: "НДФЛ: уведомление",
  REPORT_USN_NOTICE: "УСН: уведомление",
  REPORT_USN_PAY: "УСН: уплата",
  REPORT_TRANSPORT_NOTICE: "Транспортный налог: уведомление",
  REPORT_TRANSPORT_PAY: "Транспортный налог: уплата",
  REPORT_PROPERTY_PAY: "Налог на имущество: уплата",
  REPORT_INSURANCE_PAY: "Страховые взносы: уплата",
  REPORT_RSV: "РСВ (расчёт по взносам)",
  REPORT_EFS1: "ЕФС-1",
  REPORT_PSF: "ПСФ",
  REPORT_SZV_TD: "СЗВ-ТД",
  REPORT_AUSN_PAY: "Налог при АУСН: уплата",
  IFNS_DEMAND: "Требование ИФНС",
  DEMAND_RECEIPT: "Квитанция по требованию",
  CLIENT_REQUEST: "Запрос клиента",
  PAYMENT_ORDER: "Платежка",
  DIADOK: "Диадок",
  ECP: "ЭЦП",
  NOTIFICATION: "Уведомление",
  BANK_REGISTRY: "Реестр в банк",
  INVOICE: "Счёт",
  INVOICE_PAYMENT: "Оплата счёта",
  CURRENT_ACCOUNT: "Расч. счёт",
  CASH_DESK: "Касса",
  SUPPLIERS: "Поставщики",
  CUSTOMERS: "Покупатели",
  OTHER: "Другое",
};

export const TASK_TYPE_BADGES: Record<string, string> = {
  SALARY_CALC: "bg-emerald-100 text-emerald-700",
  SALARY_PAYMENT: "bg-teal-100 text-teal-700",
  SALARY_ADVANCE: "bg-lime-100 text-lime-700",
  SALARY_SICK_LEAVE: "bg-emerald-50 text-emerald-800",
  SALARY_VACATION: "bg-teal-50 text-teal-800",
  SALARY_BONUS: "bg-lime-50 text-lime-800",
  TAX_PAYMENT: "bg-orange-100 text-orange-700",
  REPORT: "bg-indigo-100 text-indigo-700",
  REPORT_VAT_DECL: "bg-indigo-50 text-indigo-800",
  REPORT_VAT_PAY: "bg-indigo-50 text-indigo-800",
  REPORT_PROFIT_DECL: "bg-indigo-50 text-indigo-800",
  REPORT_PROFIT_PAY: "bg-indigo-50 text-indigo-800",
  REPORT_NDFL_6: "bg-indigo-50 text-indigo-800",
  REPORT_NDFL_PAY: "bg-indigo-50 text-indigo-800",
  REPORT_NDFL_AUSN: "bg-indigo-50 text-indigo-800",
  REPORT_NDFL_NOTICE: "bg-indigo-50 text-indigo-800",
  REPORT_USN_NOTICE: "bg-indigo-50 text-indigo-800",
  REPORT_USN_PAY: "bg-indigo-50 text-indigo-800",
  REPORT_TRANSPORT_NOTICE: "bg-indigo-50 text-indigo-800",
  REPORT_TRANSPORT_PAY: "bg-indigo-50 text-indigo-800",
  REPORT_PROPERTY_PAY: "bg-indigo-50 text-indigo-800",
  REPORT_INSURANCE_PAY: "bg-indigo-50 text-indigo-800",
  REPORT_RSV: "bg-indigo-50 text-indigo-800",
  REPORT_EFS1: "bg-indigo-50 text-indigo-800",
  REPORT_PSF: "bg-indigo-50 text-indigo-800",
  REPORT_SZV_TD: "bg-indigo-50 text-indigo-800",
  REPORT_AUSN_PAY: "bg-indigo-50 text-indigo-800",
  IFNS_DEMAND: "bg-rose-100 text-rose-700",
  DEMAND_RECEIPT: "bg-red-100 text-red-700",
  CLIENT_REQUEST: "bg-sky-100 text-sky-700",
  PAYMENT_ORDER: "bg-cyan-100 text-cyan-700",
  DIADOK: "bg-violet-100 text-violet-700",
  ECP: "bg-fuchsia-100 text-fuchsia-700",
  NOTIFICATION: "bg-amber-100 text-amber-700",
  BANK_REGISTRY: "bg-lime-100 text-lime-700",
  INVOICE: "bg-blue-100 text-blue-700",
  INVOICE_PAYMENT: "bg-green-100 text-green-700",
  CURRENT_ACCOUNT: "bg-blue-100 text-blue-700",
  CASH_DESK: "bg-yellow-100 text-yellow-700",
  SUPPLIERS: "bg-purple-100 text-purple-700",
  CUSTOMERS: "bg-pink-100 text-pink-700",
  OTHER: "bg-zinc-100 text-zinc-600",
};
